print_fps: True

pose_estimation: 
  enable: True
  # use poseviz - visualization tool in 3D space
  poseviz: True
  # Draw skeleton of detected human on 2D image
  draw_2d: True

depth_estimation:
  enable: True
  show_depth_window: True

aruco:
  real_side_size: 0.094
  bits_marker_size: 6
  total_markers: 50