print_fps: True

pose_estimation: 
  enable: True
  poseviz: True
  draw_2d: True

depth_estimation:
  enable: True
  show_depth_window: True

aruco:
  real_side_size: 0.094
  bits_marker_size: 6
  total_markers: 50